-- Season 2 enrichment from playgroup.gg's own real records for league 997, 24 games.
-- win_con per game, fun_rating/salt_rating/mulligans_taken per known player-game.
-- Kristy/Joseph deliberately have no rows written here -- see script docstring.

UPDATE games SET win_con = 'commander_damage' WHERE id = 28;
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (28, 1, 1, 1, 0);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (28, 3, 3, 2, 2);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (28, 4, 4, 1, 0);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (28, 2, 5, 2, 0);
UPDATE games SET win_con = 'combat' WHERE id = 29;
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (29, 7, 3, 1, 1);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (29, 2, 5, 1, 1);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (29, 3, 4, 1, 2);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (29, 4, 5, 1, 2);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (30, 4, 2, 1, 1);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (30, 3, 5, 1, 1);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (30, 1, 4, 2, 0);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (31, 4, 5, 1, 0);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (31, 3, 4, 1, 0);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (31, 1, 2, 2, 0);
UPDATE games SET win_con = 'combat' WHERE id = 32;
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating) VALUES (32, 3, 5, 1);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating) VALUES (32, 4, 3, 2);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating) VALUES (32, 8, 3, 1);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (32, 1, 5, 2, 0);
UPDATE games SET win_con = 'non_combat_damage' WHERE id = 33;
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, mulligans_taken) VALUES (33, 4, 3);
UPDATE games SET win_con = 'combat' WHERE id = 34;
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (34, 4, 3, 3, 1);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (34, 2, 5, 1, 0);
UPDATE games SET win_con = 'combat' WHERE id = 35;
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (35, 7, 5, 1, 1);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (35, 2, 3, 3, 0);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (35, 4, 5, 1, 0);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (35, 3, 4, 2, 0);
UPDATE games SET win_con = 'combat' WHERE id = 36;
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (36, 7, 1, 3, 0);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (36, 3, 3, 1, 0);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (36, 2, 5, 1, 0);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (36, 1, 4, 3, 0);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (36, 4, 3, 2, 0);
UPDATE games SET win_con = 'commander_damage' WHERE id = 37;
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (37, 3, 5, 1, 1);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (37, 4, 2, 3, 2);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (37, 7, 5, 1, 0);
UPDATE games SET win_con = 'commander_damage' WHERE id = 38;
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (38, 2, 4, 1, 0);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (38, 4, 5, 1, 0);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (38, 7, 3, 1, 1);
UPDATE games SET win_con = 'combat' WHERE id = 39;
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (39, 2, 2, 2, 0);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (39, 4, 4, 2, 1);
UPDATE games SET win_con = 'commander_damage' WHERE id = 40;
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (40, 4, 3, 2, 2);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (40, 3, 4, 2, 2);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (40, 1, 4, 2, 0);
UPDATE games SET win_con = 'commander_damage' WHERE id = 41;
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (41, 3, 4, 2, 1);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (41, 1, 3, 2, 0);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (41, 4, 5, 1, 0);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (41, 2, 2, 1, 1);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (41, 7, 1, 3, 0);
UPDATE games SET win_con = 'commander_damage' WHERE id = 42;
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (42, 4, 3, 2, 0);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (42, 1, 1, 3, 0);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (42, 3, 5, 1, 0);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (42, 7, 5, 1, 0);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (42, 2, 3, 2, 0);
UPDATE games SET win_con = 'combat' WHERE id = 43;
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (43, 2, 4, 1, 1);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (43, 4, 5, 1, 0);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (43, 8, 1, 3, 0);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (43, 3, 1, 3, 0);
UPDATE games SET win_con = 'non_combat_damage' WHERE id = 44;
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (44, 2, 3, 2, 0);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (44, 8, 3, 2, 0);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (44, 4, 3, 2, 0);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (44, 3, 5, 1, 0);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (44, 1, 3, 2, 0);
UPDATE games SET win_con = 'combat' WHERE id = 45;
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (45, 2, 4, 2, 1);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (45, 4, 4, 2, 1);
UPDATE games SET win_con = 'combat' WHERE id = 47;
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (47, 2, 3, 1, 0);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (47, 1, 5, 1, 0);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (47, 3, 3, 2, 0);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (47, 4, 1, 3, 0);
UPDATE games SET win_con = 'non_combat_damage' WHERE id = 48;
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (48, 1, 5, 2, 0);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (48, 3, 5, 1, 0);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (48, 4, 5, 1, 0);
UPDATE games SET win_con = 'combat' WHERE id = 49;
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (49, 1, 4, 1, 3);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (49, 3, 5, 1, 0);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (49, 2, 4, 1, 1);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (49, 4, 4, 2, 2);
UPDATE games SET win_con = 'combat' WHERE id = 50;
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (50, 4, 2, 1, 1);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (50, 1, 3, 3, 0);
UPDATE games SET win_con = 'non_combat_damage' WHERE id = 51;
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (51, 1, 5, 1, 0);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (51, 2, 1, 3, 1);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (51, 3, 4, 1, 0);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (51, 4, 3, 1, 0);
UPDATE games SET win_con = 'non_combat_damage' WHERE id = 52;
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (52, 4, 4, 1, 0);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (52, 1, 5, 1, 0);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (52, 3, 4, 1, 0);
INSERT OR REPLACE INTO game_event_stats (game_id, player_id, fun_rating, salt_rating, mulligans_taken) VALUES (52, 2, 3, 2, 0);
